# Generated by Django 5.1.3 on 2025-01-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='today_date',
            field=models.DateTimeField(null=True),
        ),
    ]
