# Generated by Django 5.1.3 on 2025-01-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_answer_today_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='today_date',
        ),
    ]
